apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zcp-system
resources:
#- prometheus-cm.yaml
- prometheus-deployment.yaml
- prometheus-pvc.yaml
- prometheus-rbac.yaml
#- prometheus-rules.yaml
- prometheus-service.yaml
#- prometheus-user-rules.yaml
#- prometheus-zdb-rules.yaml
configMapGenerator:
- files:
  - rules/alertmanager.rules
  - rules/component-up-monitoring.rules
  - rules/elasticsearch.rules
#  - rules/etcd.rules
  - rules/kube-apiserver.rules
  - rules/kube-state-metrics.rules
  - rules/kubelet.rules
  - rules/node.rules
  - rules/prometheus.rules
  name: prometheus-rules
- files:
  - config/prometheus.yml
  name: prometheus-config
generatorOptions:
  disableNameSuffixHash: true