- op: replace
  path: /spec/rules/0/host
  value: template-monitoring.cloudzcp.io

- op: replace
  path: /spec/rules/1/host
  value: template-prometheus.cloudzcp.io

- op: replace
  path: /spec/rules/2/host
  value: template-alertmanager.cloudzcp.io

- op: replace
  path: /spec/tls/0/hosts/0
  value: template-monitoring.cloudzcp.io

- op: replace
  path: /spec/tls/0/hosts/1
  value: template-prometheus.cloudzcp.io

- op: replace
  path: /spec/tls/0/hosts/2
  value: template-alertmanager.cloudzcp.io

- op: replace
  path: /metadata/annotations/kubernetes.io~1ingress.class
  value: ingress_class