apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zcp-system
#commonLabels:
#  release: zcp-monitoring
bases:
- ../../providers/aks
#patchesStrategicMerge:
#- ingress.yaml
#- prometheus/prometheus-cm.yaml
#- grafana/grafana-cm.yaml
#- prometheus/prometheus-deployment.yaml
patchesJson6902:
- path: alertmanager/alertmanager-ingress_patch.yaml
  target:
    group: extensions
    kind: Ingress
    name: monitoring-alertmanager-ingress
    version: v1beta1
- path: grafana/grafana-ingress_patch.yaml
  target:
    group: extensions
    kind: Ingress
    name: monitoring-grafana-ingress
    version: v1beta1
- path: prometheus/prometheus-ingress_patch.yaml
  target:
    group: extensions
    kind: Ingress
    name: monitoring-prometheus-ingress
    version: v1beta1
- path: ingress_annotations_patch.yaml
  target:
    group: extensions
    kind: Ingress
    name: monitoring-alertmanager-ingress
    version: v1beta1
- path: ingress_annotations_patch.yaml
  target:
    group: extensions
    kind: Ingress
    name: monitoring-grafana-ingress
    version: v1beta1
- path: ingress_annotations_patch.yaml
  target:
    group: extensions
    kind: Ingress
    name: monitoring-prometheus-ingress
    version: v1beta1
- path: prometheus/prometheus-deployment_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: prometheus-deployment
    version: v1
configMapGenerator:
- name: prometheus-config
  namespace: zcp-system
  behavior: replace
  files:
  - prometheus/config/prometheus.yml
- name: monitoring-grafana-config
  namespace: zcp-system
  behavior: merge
  env: grafana/config.properties
secretGenerator:
- name: alertmanager-secret
  env: alertmanager/secret.properties
  type: Opaque
generatorOptions:
  disableNameSuffixHash: true
