apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zcp-system
resources:
#- alertmanager-config-cm.yaml
- alertmanager-deployment.yaml
- alertmanager-service.yaml
- alertmanager-template-cm.yaml
configMapGenerator:
- files:
  - config/config.yml
  name: alertmanager
generatorOptions:
  disableNameSuffixHash: true