apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: grafana
  name: monitoring-grafana-config-provisioning-prometheus
  namespace: zcp-system 
data:
  provisioning-database.yaml: |
    datasources:
    - name: 'prometheus'
      type: 'prometheus'
      access: 'proxy'
      org_id: 1
      url: 'http://prometheus-service:9090'
      is_default: true
      version: 1
      editable: false
